version: '2.1'
# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up
services:
  elk:
    image: dr4g0nsr/elk:1.5
    hostname: elk
    container_name: elk
    environment:
      - TZ=Europe/Belgrade
    volumes:
      - ./data:/var/lib/elasticsearch
#      - ./log:/var/log
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
      - "5044:5044"
